version: '3.8'

########################### NETWORK
networks:
  traefik:
    external: true

services:
#########################################################
## REDIS-DB
# Nextcloud (in memory) Redis Cache - speed up lookup transactions
# Speeds up Nextcloud by reducing the time spent "looking" for things
#########################################################
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - $DOCKERDIR/dashy_data/my-config.yml:/app/public/conf.yml
      - $DOCKERDIR/dashy_data/icons:/app/public/item-icons/
    # Set any environmental variables
    environment:
      - NODE_ENV=production
      - UID=0
      - GID=0
    networks:
      - traefik
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      traefik.enable: true
      ## HTTP Routers
      traefik.http.routers.dashy.entrypoints: websecure
      traefik.http.routers.dashy.rule: Host(`dash.$DOMAINNAME`)
      ## Middlewares
      traefik.http.routers.dashy.middlewares: chain-no-auth@file
      ## HTTP Services
      traefik.http.routers.dashy.service: dashy
      traefik.http.services.dashy.loadbalancer.server.port: 80
